include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Pedantic rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Additional helpful rules
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    prefer_single_quotes: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error