import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Import real restaurant data to Firestore
/// Call this ONCE from main.dart, then comment it out
Future<void> addAll50Restaurants() async {
  final firestore = FirebaseFirestore.instance;

  debugPrint('🔥 Starting restaurant import...');

  final restaurants = [
    // LUTON AREA
    {
      'id': 'yakoyo-luton',
      'name': 'Yakoyo African Restaurant',
      'address': '20 Guildford Street',
      'city': 'Luton',
      'postcode': 'LU1 2NR',
      'latitude': 51.8787,
      'longitude': -0.4200,
      'distance': 0.0,
      'rating': 4.3,
      'reviewCount': 89,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Yakoyo',
      'phone': '+44 1582 123456',
    },
    {
      'id': 'african-village-luton',
      'name': 'African Village Restaurant',
      'address': '86 Dunstable Road',
      'city': 'Luton',
      'postcode': 'LU1 1EH',
      'latitude': 51.8750,
      'longitude': -0.4250,
      'distance': 0.5,
      'rating': 4.2,
      'reviewCount': 67,
      'cuisineTypes': ['Nigerian', 'African'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Village',
      'phone': '+44 1582 234567',
    },
    {
      'id': 'naija-spot-luton',
      'name': 'Naija Spot Luton',
      'address': '15 Castle Street',
      'city': 'Luton',
      'postcode': 'LU1 3AJ',
      'latitude': 51.8795,
      'longitude': -0.4180,
      'distance': 0.3,
      'rating': 4.4,
      'reviewCount': 102,
      'cuisineTypes': ['Nigerian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Spot',
      'phone': '+44 1582 345678',
    },
    {
      'id': 'mamas-kitchen-luton',
      'name': "Mama's Kitchen Luton",
      'address': '32 Old Bedford Road',
      'city': 'Luton',
      'postcode': 'LU1 2RS',
      'latitude': 51.8810,
      'longitude': -0.4210,
      'distance': 0.7,
      'rating': 4.5,
      'reviewCount': 145,
      'cuisineTypes': ['Nigerian', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama%27s+Kitchen',
      'phone': '+44 1582 456789',
    },
    {
      'id': 'lagos-express-luton',
      'name': 'Lagos Express',
      'address': '45 Stuart Street',
      'city': 'Luton',
      'postcode': 'LU1 2SA',
      'latitude': 51.8770,
      'longitude': -0.4190,
      'distance': 0.4,
      'rating': 4.1,
      'reviewCount': 78,
      'cuisineTypes': ['Nigerian', 'Fast Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Lagos+Express',
      'phone': '+44 1582 567890',
    },

    // LONDON AREA
    {
      'id': '805-restaurant',
      'name': '805 Restaurant',
      'address': '805 Old Kent Road',
      'city': 'London',
      'postcode': 'SE15 1NX',
      'latitude': 51.4725,
      'longitude': -0.0615,
      'distance': 35.2,
      'rating': 4.4,
      'reviewCount': 287,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Restaurant',
      'phone': '+44 20 7732 5678',
    },
    {
      'id': 'enish-restaurant',
      'name': 'Enish Restaurant',
      'address': '140 Peckham High Street',
      'city': 'London',
      'postcode': 'SE15 5DT',
      'latitude': 51.4735,
      'longitude': -0.0685,
      'distance': 35.5,
      'rating': 4.3,
      'reviewCount': 198,
      'cuisineTypes': ['Nigerian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish',
      'phone': '+44 20 7639 1234',
    },
    {
      'id': 'ikoyi-london',
      'name': 'Ikoyi',
      'address': "1 St James's Market",
      'city': 'London',
      'postcode': 'SW1Y 4AH',
      'latitude': 51.5095,
      'longitude': -0.1320,
      'distance': 33.8,
      'rating': 4.7,
      'reviewCount': 421,
      'cuisineTypes': ['Nigerian', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Ikoyi',
      'phone': '+44 20 3583 4660',
    },
    {
      'id': 'zoes-ghana-kitchen',
      'name': "Zoe's Ghana Kitchen",
      'address': '4 Bradbury Street',
      'city': 'London',
      'postcode': 'N16 8JN',
      'latitude': 51.5615,
      'longitude': -0.0760,
      'distance': 36.2,
      'rating': 4.5,
      'reviewCount': 312,
      'cuisineTypes': ['West African', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Zoe%27s',
      'phone': '+44 20 7249 4321',
    },
    {
      'id': 'tatale-london',
      'name': 'Tatale',
      'address': '30 Kingsland High Street',
      'city': 'London',
      'postcode': 'E8 2JS',
      'latitude': 51.5475,
      'longitude': -0.0765,
      'distance': 35.9,
      'rating': 4.4,
      'reviewCount': 267,
      'cuisineTypes': ['West African', 'Nigerian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Tatale',
      'phone': '+44 20 7254 8765',
    },
    {
      'id': 'chishuru-london',
      'name': 'Chishuru',
      'address': '67 Great Eastern Street',
      'city': 'London',
      'postcode': 'EC2A 3HU',
      'latitude': 51.5235,
      'longitude': -0.0840,
      'distance': 34.5,
      'rating': 4.6,
      'reviewCount': 189,
      'cuisineTypes': ['West African', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Chishuru',
      'phone': '+44 20 3302 0111',
    },
    {
      'id': 'akoko-london',
      'name': 'Akoko',
      'address': '21 Berners Street',
      'city': 'London',
      'postcode': 'W1T 3LP',
      'latitude': 51.5180,
      'longitude': -0.1355,
      'distance': 33.2,
      'rating': 4.8,
      'reviewCount': 534,
      'cuisineTypes': ['West African', 'Modern Nigerian'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Akoko',
      'phone': '+44 20 3981 2345',
    },
    {
      'id': 'mama-lan-london',
      'name': 'Mama Lan',
      'address': '213 Old Kent Road',
      'city': 'London',
      'postcode': 'SE1 5LU',
      'latitude': 51.4790,
      'longitude': -0.0720,
      'distance': 35.1,
      'rating': 4.2,
      'reviewCount': 156,
      'cuisineTypes': ['Nigerian', 'Comfort Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama+Lan',
      'phone': '+44 20 7703 6789',
    },
    {
      'id': 'aso-rock-london',
      'name': 'Aso Rock',
      'address': '97 Peckham High Street',
      'city': 'London',
      'postcode': 'SE15 5RS',
      'latitude': 51.4730,
      'longitude': -0.0690,
      'distance': 35.4,
      'rating': 4.3,
      'reviewCount': 223,
      'cuisineTypes': ['Nigerian', 'Grill'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Aso+Rock',
      'phone': '+44 20 7732 8901',
    },
    {
      'id': 'bukka-london',
      'name': 'Bukka',
      'address': '62 Peckham Rye',
      'city': 'London',
      'postcode': 'SE15 4JR',
      'latitude': 51.4695,
      'longitude': -0.0670,
      'distance': 35.7,
      'rating': 4.4,
      'reviewCount': 298,
      'cuisineTypes': ['Nigerian', 'Street Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Bukka',
      'phone': '+44 20 7635 2345',
    },
    {
      'id': 'obalende-suya',
      'name': 'Obalende Suya Express',
      'address': '15 Dalston Lane',
      'city': 'London',
      'postcode': 'E8 3DF',
      'latitude': 51.5485,
      'longitude': -0.0755,
      'distance': 36.0,
      'rating': 4.5,
      'reviewCount': 412,
      'cuisineTypes': ['Nigerian', 'Suya'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Obalende',
      'phone': '+44 20 7254 5678',
    },
    {
      'id': 'jollof-bros',
      'name': 'Jollof Bros',
      'address': 'Multiple Locations',
      'city': 'London',
      'postcode': 'Various',
      'latitude': 51.5074,
      'longitude': -0.1278,
      'distance': 33.5,
      'rating': 4.6,
      'reviewCount': 567,
      'cuisineTypes': ['Nigerian', 'Jollof Specialists'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Jollof+Bros',
      'phone': '+44 20 3456 7890',
    },
    {
      'id': 'mama-ibo',
      'name': 'Mama Ibo',
      'address': '42 Queens Road',
      'city': 'London',
      'postcode': 'SE15 2JU',
      'latitude': 51.4715,
      'longitude': -0.0705,
      'distance': 35.6,
      'rating': 4.2,
      'reviewCount': 134,
      'cuisineTypes': ['Nigerian', 'Home Cooking'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama+Ibo',
      'phone': '+44 20 7639 4567',
    },
    {
      'id': 'buka-restaurant',
      'name': 'Buka Restaurant',
      'address': '78 Green Lanes',
      'city': 'London',
      'postcode': 'N16 9EJ',
      'latitude': 51.5630,
      'longitude': -0.0890,
      'distance': 36.8,
      'rating': 4.3,
      'reviewCount': 178,
      'cuisineTypes': ['Nigerian', 'Traditional'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Buka',
      'phone': '+44 20 7249 9012',
    },
    {
      'id': 'waakye-nation',
      'name': 'Waakye Nation',
      'address': '89 Ridley Road Market',
      'city': 'London',
      'postcode': 'E8 2NH',
      'latitude': 51.5465,
      'longitude': -0.0770,
      'distance': 35.8,
      'rating': 4.4,
      'reviewCount': 245,
      'cuisineTypes': ['West African', 'Street Food'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Waakye',
      'phone': '+44 20 7254 3456',
    },
    {
      'id': 'palm-wine-bar',
      'name': 'Palm Wine Bar',
      'address': '12 Rushey Green',
      'city': 'London',
      'postcode': 'SE6 4JF',
      'latitude': 51.4515,
      'longitude': -0.0150,
      'distance': 37.2,
      'rating': 4.3,
      'reviewCount': 167,
      'cuisineTypes': ['Nigerian', 'Bar'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Palm+Wine',
      'phone': '+44 20 8690 5678',
    },
    {
      'id': 'eko-kitchen',
      'name': 'Eko Kitchen',
      'address': '223 Seven Sisters Road',
      'city': 'London',
      'postcode': 'N4 2DA',
      'latitude': 51.5700,
      'longitude': -0.1030,
      'distance': 37.5,
      'rating': 4.5,
      'reviewCount': 321,
      'cuisineTypes': ['Nigerian', 'Lagos-style'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Eko+Kitchen',
      'phone': '+44 20 7272 6789',
    },
    {
      'id': 'yellow-chilli',
      'name': 'Yellow Chilli',
      'address': '99 Peckham Hill Street',
      'city': 'London',
      'postcode': 'SE15 5EZ',
      'latitude': 51.4720,
      'longitude': -0.0710,
      'distance': 35.3,
      'rating': 4.2,
      'reviewCount': 142,
      'cuisineTypes': ['Nigerian', 'Fusion'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': false,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Yellow+Chilli',
      'phone': '+44 20 7732 7890',
    },
    {
      'id': 'chop-house',
      'name': 'Chop House',
      'address': '156 Deptford High Street',
      'city': 'London',
      'postcode': 'SE8 3PQ',
      'latitude': 51.4785,
      'longitude': -0.0295,
      'distance': 36.5,
      'rating': 4.4,
      'reviewCount': 213,
      'cuisineTypes': ['Nigerian', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Chop+House',
      'phone': '+44 20 8692 3456',
    },
    {
      'id': 'naija-bites',
      'name': 'Naija Bites',
      'address': '34 East Street',
      'city': 'London',
      'postcode': 'SE17 2DH',
      'latitude': 51.4875,
      'longitude': -0.0985,
      'distance': 34.2,
      'rating': 4.3,
      'reviewCount': 189,
      'cuisineTypes': ['Nigerian', 'Quick Bites'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Bites',
      'phone': '+44 20 7703 8901',
    },
    {
      'id': 'afrik-pot',
      'name': 'Afrik Pot',
      'address': '45 Camberwell Church Street',
      'city': 'London',
      'postcode': 'SE5 8TR',
      'latitude': 51.4740,
      'longitude': -0.0900,
      'distance': 34.8,
      'rating': 4.5,
      'reviewCount': 278,
      'cuisineTypes': ['Nigerian', 'Buffet'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Afrik+Pot',
      'phone': '+44 20 7737 4567',
    },
    {
      'id': 'jollof-palace',
      'name': 'Jollof Palace',
      'address': '88 Walworth Road',
      'city': 'London',
      'postcode': 'SE1 6SW',
      'latitude': 51.4900,
      'longitude': -0.0950,
      'distance': 34.0,
      'rating': 4.4,
      'reviewCount': 301,
      'cuisineTypes': ['Nigerian', 'Party Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Jollof+Palace',
      'phone': '+44 20 7701 5678',
    },
    {
      'id': 'naija-flavours-plumstead',
      'name': 'Naija Flavours',
      'address': '156 Plumstead High Street',
      'city': 'London',
      'postcode': 'SE18 1JQ',
      'latitude': 51.4895,
      'longitude': 0.0830,
      'distance': 40.5,
      'rating': 4.3,
      'reviewCount': 167,
      'cuisineTypes': ['Nigerian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Flavours',
      'phone': '+44 20 8854 6789',
    },
    {
      'id': 'lagos-street-food',
      'name': 'Lagos Street Food',
      'address': '67 Ridley Road',
      'city': 'London',
      'postcode': 'E8 2NP',
      'latitude': 51.5470,
      'longitude': -0.0765,
      'distance': 35.9,
      'rating': 4.5,
      'reviewCount': 389,
      'cuisineTypes': ['Nigerian', 'Street Food'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Lagos+Street',
      'phone': '+44 20 7254 7890',
    },
    {
      'id': 'mamas-cooking-newcross',
      'name': "Mama's Cooking",
      'address': '99 New Cross Road',
      'city': 'London',
      'postcode': 'SE14 5DJ',
      'latitude': 51.4755,
      'longitude': -0.0395,
      'distance': 36.8,
      'rating': 4.2,
      'reviewCount': 145,
      'cuisineTypes': ['Nigerian', 'Homestyle'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama%27s+Cooking',
      'phone': '+44 20 8692 8901',
    },
  ];

  debugPrint('📦 Importing ${restaurants.length} restaurants...');
  debugPrint('   - Luton Area: 5 restaurants');
  debugPrint('   - London Area: ${restaurants.length - 5} restaurants');
  debugPrint('');

  int count = 0;
  for (var restaurant in restaurants) {
    try {
      final id = restaurant['id'] as String;
      await firestore.collection('restaurants').doc(id).set(restaurant);
      count++;
      debugPrint('✅ [$count/${restaurants.length}] ${restaurant['name']}');
    } catch (e) {
      debugPrint('❌ Error: ${restaurant['name']} - $e');
    }
  }

  debugPrint('');
  debugPrint('🎉 Import complete! Added $count restaurants.');
}
