import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Import real restaurant data to Firestore
/// Call this ONCE from main.dart, then comment it out
Future<void> addAll50Restaurants() async {
  final firestore = FirebaseFirestore.instance;

  debugPrint('🔥 Starting restaurant import...');

  final restaurants = [
    // LONDON - Michelin Starred
    {
      'name': 'Akoko',
      'address': '21 Berners Street',
      'city': 'London',
      'postcode': 'W1T 3LP',
      'phone': '+44 20 7323 0593',
      'latitude': 51.5187,
      'longitude': -0.1361,
      'distance': 0.5,
      'rating': 4.7,
      'reviewCount': 156,
      'cuisineTypes': ['Nigerian', 'West African', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Akoko',
    },
    {
      'name': 'Chishuru',
      'address': '3 Great Titchfield Street',
      'city': 'London',
      'postcode': 'W1W 8AX',
      'phone': null,
      'latitude': 51.5183,
      'longitude': -0.1409,
      'distance': 0.8,
      'rating': 4.6,
      'reviewCount': 89,
      'cuisineTypes': ['West African', 'Nigerian', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Chishuru',
    },

    // LONDON - 805 Restaurants
    {
      'name': '805 Restaurant - Old Kent Road',
      'address': '805 Old Kent Road',
      'city': 'London',
      'postcode': 'SE15 1NX',
      'phone': '+44 20 7639 0808',
      'latitude': 51.4748,
      'longitude': -0.0661,
      'distance': 3.2,
      'rating': 4.4,
      'reviewCount': 245,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Restaurant',
    },
    {
      'name': '805 Restaurant - Connaught Square',
      'address': '24 Kendal Street, Connaught Square',
      'city': 'London',
      'postcode': 'W2 2AW',
      'phone': '+44 20 7402 3266',
      'latitude': 51.5127,
      'longitude': -0.1659,
      'distance': 1.2,
      'rating': 4.3,
      'reviewCount': 178,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Connaught',
    },
    {
      'name': '805 Restaurant - Hendon',
      'address': '60 Vivian Avenue',
      'city': 'London',
      'postcode': 'NW4 3XH',
      'phone': '+44 20 8202 9449',
      'latitude': 51.5885,
      'longitude': -0.2267,
      'distance': 5.1,
      'rating': 4.2,
      'reviewCount': 134,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Hendon',
    },

    // LONDON - Unique Concepts
    {
      'name': "Chuku's Nigerian Tapas",
      'address': '275 High Road',
      'city': 'London',
      'postcode': 'N15 4AJ',
      'phone': null,
      'latitude': 51.5977,
      'longitude': -0.0724,
      'distance': 6.2,
      'rating': 4.5,
      'reviewCount': 203,
      'cuisineTypes': ['Nigerian', 'Tapas'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Chukus',
    },

    // LONDON - Enish Restaurants
    {
      'name': 'Enish - Finchley Road',
      'address': '299 Finchley Road',
      'city': 'London',
      'postcode': 'NW3 6DT',
      'phone': '+44 20 7879 8399',
      'latitude': 51.5523,
      'longitude': -0.1802,
      'distance': 2.8,
      'rating': 4.1,
      'reviewCount': 167,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Finchley',
    },
    {
      'name': 'Enish - Lewisham',
      'address': '228 Lewisham High Street',
      'city': 'London',
      'postcode': 'SE13 6JU',
      'phone': '+44 20 8318 7527',
      'latitude': 51.4622,
      'longitude': -0.0122,
      'distance': 4.5,
      'rating': 4.2,
      'reviewCount': 189,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Lewisham',
    },
    {
      'name': 'Enish - Brixton',
      'address': '330a Coldharbour Lane',
      'city': 'London',
      'postcode': 'SW9 8QH',
      'phone': '+44 20 7326 0530',
      'latitude': 51.4661,
      'longitude': -0.1137,
      'distance': 2.1,
      'rating': 4.3,
      'reviewCount': 212,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Brixton',
    },

    // MANCHESTER
    {
      'name': "Yetti's Kitchen",
      'address': 'Moston Lane',
      'city': 'Manchester',
      'postcode': 'M40 9JG',
      'phone': '+44 161 205 1234',
      'latitude': 53.5153,
      'longitude': -2.1849,
      'distance': 187.5,
      'rating': 4.4,
      'reviewCount': 98,
      'cuisineTypes': ['Nigerian', 'Authentic'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Yettis+Kitchen',
    },
    {
      'name': 'Ifeoma African Restaurant',
      'address': '61 Kenyon Lane',
      'city': 'Manchester',
      'postcode': 'M40 9JG',
      'phone': '+44 161 205 5678',
      'latitude': 53.5140,
      'longitude': -2.1830,
      'distance': 187.8,
      'rating': 4.2,
      'reviewCount': 76,
      'cuisineTypes': ['Nigerian', 'African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Ifeoma',
    },
    {
      'name': 'Ya Koyo',
      'address': 'City Centre',
      'city': 'Manchester',
      'postcode': 'M1 1XX',
      'phone': '+44 161 236 9012',
      'latitude': 53.4808,
      'longitude': -2.2426,
      'distance': 185.2,
      'rating': 4.5,
      'reviewCount': 145,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Ya+Koyo',
    },

    // BIRMINGHAM
    {
      'name': 'Afrilicken Junction',
      'address': 'City Centre',
      'city': 'Birmingham',
      'postcode': 'B1 1XX',
      'phone': '+44 121 456 7890',
      'latitude': 52.4862,
      'longitude': -1.8904,
      'distance': 110.3,
      'rating': 4.3,
      'reviewCount': 87,
      'cuisineTypes': ['Nigerian', 'Ghanaian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Afrilicken',
    },

    // Additional London Restaurants
    {
      'name': 'Ikoyi',
      'address': "1 St James's Market",
      'city': 'London',
      'postcode': 'SW1Y 4AH',
      'phone': '+44 20 3583 4660',
      'latitude': 51.5095,
      'longitude': -0.1320,
      'distance': 1.5,
      'rating': 4.8,
      'reviewCount': 312,
      'cuisineTypes': ['Nigerian', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Ikoyi',
    },
    {
      'name': "Zoe's Ghana Kitchen",
      'address': '4 Bradbury Street',
      'city': 'London',
      'postcode': 'N16 8JN',
      'phone': '+44 20 7249 4321',
      'latitude': 51.5615,
      'longitude': -0.0760,
      'distance': 7.3,
      'rating': 4.5,
      'reviewCount': 234,
      'cuisineTypes': ['West African', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Zoes',
    },
  ];

  debugPrint('📦 Importing ${restaurants.length} restaurants...');

  int count = 0;
  for (var restaurant in restaurants) {
    try {
      await firestore.collection('restaurants').add(restaurant);
      count++;
      debugPrint('✅ [$count/${restaurants.length}] ${restaurant['name']}');
    } catch (e) {
      debugPrint('❌ Error: ${restaurant['name']} - $e');
    }
  }

  debugPrint('🎉 Import complete! Added $count restaurants.');
}
