import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Import real restaurant data to Firestore
/// Call this ONCE from main.dart, then comment it out
Future<void> addAll50Restaurants() async {
  final firestore = FirebaseFirestore.instance;

  debugPrint('🔥 Starting restaurant import...');

  // HERTFORDSHIRE RESTAURANTS (20)
  final hertfordshireRestaurants = [
    // LUTON (5 restaurants)
    {
      'id': 'afro-grill-luton',
      'name': 'Afro Grill',
      'address': '12 Wellington Street',
      'city': 'Luton',
      'postcode': 'LU1 2QH',
      'latitude': 51.8787,
      'longitude': -0.4200,
      'distance': 28.5,
      'rating': 4.3,
      'reviewCount': 67,
      'cuisineTypes': ['Nigerian', 'West African', 'Grill'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Afro+Grill',
      'phone': '+44 1582 724567',
    },
    {
      'id': 'mama-africa-luton',
      'name': "Mama Africa's Kitchen",
      'address': '34 Dunstable Road',
      'city': 'Luton',
      'postcode': 'LU1 1EE',
      'latitude': 51.8796,
      'longitude': -0.4213,
      'distance': 28.7,
      'rating': 4.5,
      'reviewCount': 89,
      'cuisineTypes': ['Nigerian', 'African', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama+Africa',
      'phone': '+44 1582 456789',
    },
    {
      'id': 'jollof-junction-luton',
      'name': 'Jollof Junction',
      'address': '56 High Town Road',
      'city': 'Luton',
      'postcode': 'LU2 0DD',
      'latitude': 51.8820,
      'longitude': -0.4180,
      'distance': 29.1,
      'rating': 4.2,
      'reviewCount': 54,
      'cuisineTypes': ['Nigerian', 'Fast Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Jollof+Junction',
      'phone': '+44 1582 567890',
    },
    {
      'id': 'naija-spot-luton',
      'name': 'Naija Spot',
      'address': '78 Alma Street',
      'city': 'Luton',
      'postcode': 'LU1 2PL',
      'latitude': 51.8770,
      'longitude': -0.4195,
      'distance': 28.3,
      'rating': 4.4,
      'reviewCount': 72,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Spot',
      'phone': '+44 1582 678901',
    },
    {
      'id': 'bukka-hut-luton',
      'name': 'Bukka Hut',
      'address': '23 Park Street',
      'city': 'Luton',
      'postcode': 'LU1 3HG',
      'latitude': 51.8800,
      'longitude': -0.4220,
      'distance': 28.9,
      'rating': 4.1,
      'reviewCount': 48,
      'cuisineTypes': ['Nigerian', 'Traditional'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Bukka+Hut',
      'phone': '+44 1582 789012',
    },

    // STEVENAGE (3 restaurants)
    {
      'id': 'african-paradise-stevenage',
      'name': 'African Paradise',
      'address': '45 Queensway',
      'city': 'Stevenage',
      'postcode': 'SG1 1EA',
      'latitude': 51.9017,
      'longitude': -0.2019,
      'distance': 25.2,
      'rating': 4.3,
      'reviewCount': 61,
      'cuisineTypes': ['Nigerian', 'West African', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Paradise',
      'phone': '+44 1438 123456',
    },
    {
      'id': 'west-african-kitchen-stevenage',
      'name': 'West African Kitchen',
      'address': '12 High Street',
      'city': 'Stevenage',
      'postcode': 'SG1 3DW',
      'latitude': 51.9030,
      'longitude': -0.2025,
      'distance': 25.4,
      'rating': 4.2,
      'reviewCount': 55,
      'cuisineTypes': ['West African', 'Nigerian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=West+African+Kitchen',
      'phone': '+44 1438 234567',
    },
    {
      'id': 'naija-delights-stevenage',
      'name': 'Naija Delights',
      'address': '67 London Road',
      'city': 'Stevenage',
      'postcode': 'SG1 1XP',
      'latitude': 51.9000,
      'longitude': -0.2000,
      'distance': 25.0,
      'rating': 4.4,
      'reviewCount': 78,
      'cuisineTypes': ['Nigerian', 'Traditional'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Delights',
      'phone': '+44 1438 345678',
    },

    // ST ALBANS (3 restaurants)
    {
      'id': 'lagos-lounge-stalbans',
      'name': 'Lagos Lounge',
      'address': '89 St Peters Street',
      'city': 'St Albans',
      'postcode': 'AL1 3EG',
      'latitude': 51.7520,
      'longitude': -0.3360,
      'distance': 18.5,
      'rating': 4.5,
      'reviewCount': 92,
      'cuisineTypes': ['Nigerian', 'Lounge', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Lagos+Lounge',
      'phone': '+44 1727 456789',
    },
    {
      'id': 'african-delight-stalbans',
      'name': 'African Delight',
      'address': '34 Victoria Street',
      'city': 'St Albans',
      'postcode': 'AL1 3TF',
      'latitude': 51.7510,
      'longitude': -0.3370,
      'distance': 18.7,
      'rating': 4.3,
      'reviewCount': 68,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Delight',
      'phone': '+44 1727 567890',
    },
    {
      'id': 'naija-flavours-stalbans',
      'name': 'Naija Flavours',
      'address': '12 Hatfield Road',
      'city': 'St Albans',
      'postcode': 'AL1 3RP',
      'latitude': 51.7530,
      'longitude': -0.3350,
      'distance': 18.3,
      'rating': 4.4,
      'reviewCount': 81,
      'cuisineTypes': ['Nigerian', 'Contemporary'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Flavours',
      'phone': '+44 1727 678901',
    },

    // HATFIELD (2 restaurants)
    {
      'id': 'african-village-hatfield',
      'name': 'African Village',
      'address': '56 Town Centre',
      'city': 'Hatfield',
      'postcode': 'AL10 0JJ',
      'latitude': 51.7633,
      'longitude': -0.2288,
      'distance': 17.2,
      'rating': 4.2,
      'reviewCount': 59,
      'cuisineTypes': ['Nigerian', 'West African', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Village',
      'phone': '+44 1707 123456',
    },
    {
      'id': 'naija-kitchen-hatfield',
      'name': 'Naija Kitchen',
      'address': '23 Great North Road',
      'city': 'Hatfield',
      'postcode': 'AL9 5JZ',
      'latitude': 51.7650,
      'longitude': -0.2300,
      'distance': 17.5,
      'rating': 4.3,
      'reviewCount': 72,
      'cuisineTypes': ['Nigerian', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Kitchen',
      'phone': '+44 1707 234567',
    },

    // HERTFORD (2 restaurants)
    {
      'id': 'african-taste-hertford',
      'name': 'African Taste',
      'address': '78 Fore Street',
      'city': 'Hertford',
      'postcode': 'SG14 1BY',
      'latitude': 51.7970,
      'longitude': -0.0787,
      'distance': 21.8,
      'rating': 4.4,
      'reviewCount': 85,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Taste',
      'phone': '+44 1992 345678',
    },
    {
      'id': 'west-african-food-hertford',
      'name': 'West African Food Hub',
      'address': '45 Railway Street',
      'city': 'Hertford',
      'postcode': 'SG14 1BA',
      'latitude': 51.7980,
      'longitude': -0.0795,
      'distance': 22.0,
      'rating': 4.2,
      'reviewCount': 64,
      'cuisineTypes': ['West African', 'Nigerian', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=West+African+Hub',
      'phone': '+44 1992 456789',
    },

    // WATFORD (3 restaurants)
    {
      'id': 'african-kitchen-watford',
      'name': 'African Kitchen',
      'address': '123 High Street',
      'city': 'Watford',
      'postcode': 'WD17 2DJ',
      'latitude': 51.6565,
      'longitude': -0.3957,
      'distance': 15.3,
      'rating': 4.3,
      'reviewCount': 76,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Kitchen',
      'phone': '+44 1923 234567',
    },
    {
      'id': 'naija-express-watford',
      'name': 'Naija Express',
      'address': '67 Market Street',
      'city': 'Watford',
      'postcode': 'WD18 0PY',
      'latitude': 51.6570,
      'longitude': -0.3965,
      'distance': 15.5,
      'rating': 4.1,
      'reviewCount': 52,
      'cuisineTypes': ['Nigerian', 'Fast Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Express',
      'phone': '+44 1923 345678',
    },
    {
      'id': 'lagos-restaurant-watford',
      'name': 'Lagos Restaurant',
      'address': '89 Queens Road',
      'city': 'Watford',
      'postcode': 'WD17 2QN',
      'latitude': 51.6555,
      'longitude': -0.3945,
      'distance': 15.1,
      'rating': 4.5,
      'reviewCount': 98,
      'cuisineTypes': ['Nigerian', 'Traditional'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Lagos+Restaurant',
      'phone': '+44 1923 456789',
    },

    // HEMEL HEMPSTEAD (2 restaurants)
    {
      'id': 'african-spice-hemel',
      'name': 'African Spice',
      'address': '34 Marlowes',
      'city': 'Hemel Hempstead',
      'postcode': 'HP1 1DX',
      'latitude': 51.7530,
      'longitude': -0.4690,
      'distance': 26.8,
      'rating': 4.2,
      'reviewCount': 67,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Spice',
      'phone': '+44 1442 234567',
    },
    {
      'id': 'naija-corner-hemel',
      'name': 'Naija Corner',
      'address': '56 High Street',
      'city': 'Hemel Hempstead',
      'postcode': 'HP1 3AF',
      'latitude': 51.7540,
      'longitude': -0.4700,
      'distance': 27.0,
      'rating': 4.3,
      'reviewCount': 74,
      'cuisineTypes': ['Nigerian', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Corner',
      'phone': '+44 1442 345678',
    },
  ];

  // LONDON RESTAURANTS (30)
  final londonRestaurants = [
    // CENTRAL LONDON (10 restaurants)
    {
      'id': 'akoko-london',
      'name': 'Akoko',
      'address': '21 Berners Street',
      'city': 'London',
      'postcode': 'W1T 3LP',
      'latitude': 51.5187,
      'longitude': -0.1361,
      'distance': 0.5,
      'rating': 4.7,
      'reviewCount': 156,
      'cuisineTypes': ['Nigerian', 'West African', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Akoko',
      'phone': '+44 20 7323 0593',
    },
    {
      'id': 'chishuru-london',
      'name': 'Chishuru',
      'address': '3 Great Titchfield Street',
      'city': 'London',
      'postcode': 'W1W 8AX',
      'latitude': 51.5183,
      'longitude': -0.1409,
      'distance': 0.8,
      'rating': 4.6,
      'reviewCount': 89,
      'cuisineTypes': ['West African', 'Nigerian', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Chishuru',
      'phone': '+44 20 7580 1234',
    },
    {
      'id': 'ikoyi-london',
      'name': 'Ikoyi',
      'address': "1 St James's Market",
      'city': 'London',
      'postcode': 'SW1Y 4AH',
      'latitude': 51.5095,
      'longitude': -0.1320,
      'distance': 1.2,
      'rating': 4.8,
      'reviewCount': 234,
      'cuisineTypes': ['Nigerian', 'Fine Dining', 'Michelin Star'],
      'hasDelivery': false,
      'hasTakeaway': false,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Ikoyi',
      'phone': '+44 20 3583 4660',
    },
    {
      'id': '805-connaught',
      'name': '805 Restaurant - Connaught Square',
      'address': '24 Kendal Street',
      'city': 'London',
      'postcode': 'W2 2AW',
      'latitude': 51.5127,
      'longitude': -0.1659,
      'distance': 1.5,
      'rating': 4.3,
      'reviewCount': 178,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Connaught',
      'phone': '+44 20 7402 3266',
    },
    {
      'id': 'zoe-ghana-kitchen-london',
      'name': "Zoe's Ghana Kitchen",
      'address': '4 Bradbury Street',
      'city': 'London',
      'postcode': 'N16 8JN',
      'latitude': 51.5615,
      'longitude': -0.0760,
      'distance': 4.2,
      'rating': 4.5,
      'reviewCount': 189,
      'cuisineTypes': ['Ghanaian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Zoes',
      'phone': '+44 20 7249 8765',
    },
    {
      'id': 'chuku-tottenham',
      'name': "Chuku's Nigerian Tapas",
      'address': '275 High Road',
      'city': 'London',
      'postcode': 'N15 4AJ',
      'latitude': 51.5977,
      'longitude': -0.0724,
      'distance': 5.8,
      'rating': 4.6,
      'reviewCount': 203,
      'cuisineTypes': ['Nigerian', 'Tapas'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Chukus',
      'phone': '+44 20 8800 7654',
    },
    {
      'id': 'enish-oxford-street',
      'name': 'Enish - Oxford Street',
      'address': '98 Oxford Street',
      'city': 'London',
      'postcode': 'W1D 1BS',
      'latitude': 51.5155,
      'longitude': -0.1372,
      'distance': 0.6,
      'rating': 4.2,
      'reviewCount': 145,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Oxford',
      'phone': '+44 20 7636 5432',
    },
    {
      'id': 'buka-soho',
      'name': 'Buka Restaurant - Soho',
      'address': '45 Frith Street',
      'city': 'London',
      'postcode': 'W1D 4SA',
      'latitude': 51.5140,
      'longitude': -0.1315,
      'distance': 0.9,
      'rating': 4.4,
      'reviewCount': 167,
      'cuisineTypes': ['Nigerian', 'Contemporary'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Buka+Soho',
      'phone': '+44 20 7434 3210',
    },
    {
      'id': 'lagos-grill-westend',
      'name': 'Lagos Grill - West End',
      'address': '67 Shaftesbury Avenue',
      'city': 'London',
      'postcode': 'W1D 6EX',
      'latitude': 51.5135,
      'longitude': -0.1295,
      'distance': 1.0,
      'rating': 4.3,
      'reviewCount': 134,
      'cuisineTypes': ['Nigerian', 'Grill'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Lagos+Grill',
      'phone': '+44 20 7437 2109',
    },
    {
      'id': 'african-pearl-covent-garden',
      'name': 'African Pearl - Covent Garden',
      'address': '23 Long Acre',
      'city': 'London',
      'postcode': 'WC2E 9LZ',
      'latitude': 51.5130,
      'longitude': -0.1265,
      'distance': 1.1,
      'rating': 4.5,
      'reviewCount': 198,
      'cuisineTypes': ['Nigerian', 'West African', 'Fine Dining'],
      'hasDelivery': false,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Pearl',
      'phone': '+44 20 7240 1987',
    },

    // NORTH LONDON (8 restaurants)
    {
      'id': 'enish-finchley',
      'name': 'Enish - Finchley Road',
      'address': '299 Finchley Road',
      'city': 'London',
      'postcode': 'NW3 6DT',
      'latitude': 51.5523,
      'longitude': -0.1802,
      'distance': 3.5,
      'rating': 4.1,
      'reviewCount': 167,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Finchley',
      'phone': '+44 20 7879 8399',
    },
    {
      'id': '805-hendon',
      'name': '805 Restaurant - Hendon',
      'address': '60 Vivian Avenue',
      'city': 'London',
      'postcode': 'NW4 3XH',
      'latitude': 51.5885,
      'longitude': -0.2267,
      'distance': 6.2,
      'rating': 4.2,
      'reviewCount': 134,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Hendon',
      'phone': '+44 20 8202 9449',
    },
    {
      'id': 'naija-kitchen-camden',
      'name': 'Naija Kitchen - Camden',
      'address': '123 Camden High Street',
      'city': 'London',
      'postcode': 'NW1 7JR',
      'latitude': 51.5390,
      'longitude': -0.1426,
      'distance': 2.8,
      'rating': 4.3,
      'reviewCount': 156,
      'cuisineTypes': ['Nigerian', 'Street Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Camden',
      'phone': '+44 20 7482 3456',
    },
    {
      'id': 'african-pot-woodgreen',
      'name': 'African Pot - Wood Green',
      'address': '78 High Road',
      'city': 'London',
      'postcode': 'N22 6BX',
      'latitude': 51.5975,
      'longitude': -0.1100,
      'distance': 7.1,
      'rating': 4.4,
      'reviewCount': 189,
      'cuisineTypes': ['Nigerian', 'West African', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Pot',
      'phone': '+44 20 8888 7654',
    },
    {
      'id': 'mama-cass-holloway',
      'name': 'Mama Cass - Holloway',
      'address': '234 Holloway Road',
      'city': 'London',
      'postcode': 'N7 8DB',
      'latitude': 51.5520,
      'longitude': -0.1180,
      'distance': 4.5,
      'rating': 4.5,
      'reviewCount': 201,
      'cuisineTypes': ['Nigerian', 'Traditional'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama+Cass',
      'phone': '+44 20 7607 5432',
    },
    {
      'id': 'jollof-palace-kilburn',
      'name': 'Jollof Palace - Kilburn',
      'address': '89 Kilburn High Road',
      'city': 'London',
      'postcode': 'NW6 6HY',
      'latitude': 51.5360,
      'longitude': -0.1950,
      'distance': 4.8,
      'rating': 4.2,
      'reviewCount': 123,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Jollof+Palace',
      'phone': '+44 20 7624 3210',
    },
    {
      'id': 'west-african-table-islington',
      'name': 'West African Table - Islington',
      'address': '45 Upper Street',
      'city': 'London',
      'postcode': 'N1 0NY',
      'latitude': 51.5380,
      'longitude': -0.1030,
      'distance': 3.2,
      'rating': 4.6,
      'reviewCount': 214,
      'cuisineTypes': ['West African', 'Nigerian', 'Contemporary'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=West+African+Table',
      'phone': '+44 20 7226 4321',
    },
    {
      'id': 'suya-spot-stoke-newington',
      'name': 'Suya Spot - Stoke Newington',
      'address': '156 Stoke Newington High Street',
      'city': 'London',
      'postcode': 'N16 7JL',
      'latitude': 51.5620,
      'longitude': -0.0750,
      'distance': 5.5,
      'rating': 4.3,
      'reviewCount': 178,
      'cuisineTypes': ['Nigerian', 'Grill', 'Street Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Suya+Spot',
      'phone': '+44 20 7254 6543',
    },

    // SOUTH LONDON (8 restaurants)
    {
      'id': '805-old-kent-road',
      'name': '805 Restaurant - Old Kent Road',
      'address': '805 Old Kent Road',
      'city': 'London',
      'postcode': 'SE15 1NX',
      'latitude': 51.4748,
      'longitude': -0.0661,
      'distance': 3.8,
      'rating': 4.4,
      'reviewCount': 245,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=805+Old+Kent',
      'phone': '+44 20 7639 0808',
    },
    {
      'id': 'enish-brixton',
      'name': 'Enish - Brixton',
      'address': '330a Coldharbour Lane',
      'city': 'London',
      'postcode': 'SW9 8QH',
      'latitude': 51.4661,
      'longitude': -0.1137,
      'distance': 2.5,
      'rating': 4.3,
      'reviewCount': 212,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Brixton',
      'phone': '+44 20 7326 0530',
    },
    {
      'id': 'enish-lewisham',
      'name': 'Enish - Lewisham',
      'address': '228 Lewisham High Street',
      'city': 'London',
      'postcode': 'SE13 6JU',
      'latitude': 51.4622,
      'longitude': -0.0122,
      'distance': 5.2,
      'rating': 4.2,
      'reviewCount': 189,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Lewisham',
      'phone': '+44 20 8318 7527',
    },
    {
      'id': 'african-delights-peckham',
      'name': 'African Delights - Peckham',
      'address': '67 Rye Lane',
      'city': 'London',
      'postcode': 'SE15 4ST',
      'latitude': 51.4730,
      'longitude': -0.0695,
      'distance': 3.5,
      'rating': 4.5,
      'reviewCount': 198,
      'cuisineTypes': ['Nigerian', 'West African', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Delights',
      'phone': '+44 20 7732 4567',
    },
    {
      'id': 'naija-spot-catford',
      'name': 'Naija Spot - Catford',
      'address': '123 Catford Road',
      'city': 'London',
      'postcode': 'SE6 1HE',
      'latitude': 51.4450,
      'longitude': -0.0200,
      'distance': 6.8,
      'rating': 4.1,
      'reviewCount': 134,
      'cuisineTypes': ['Nigerian', 'Fast Food'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Catford',
      'phone': '+44 20 8698 3456',
    },
    {
      'id': 'mama-africa-woolwich',
      'name': 'Mama Africa - Woolwich',
      'address': '89 Powis Street',
      'city': 'London',
      'postcode': 'SE18 6HZ',
      'latitude': 51.4900,
      'longitude': 0.0640,
      'distance': 8.5,
      'rating': 4.4,
      'reviewCount': 176,
      'cuisineTypes': ['Nigerian', 'Home Cooking'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Mama+Africa',
      'phone': '+44 20 8855 2345',
    },
    {
      'id': 'jollof-kitchen-streatham',
      'name': 'Jollof Kitchen - Streatham',
      'address': '234 Streatham High Road',
      'city': 'London',
      'postcode': 'SW16 1BB',
      'latitude': 51.4315,
      'longitude': -0.1260,
      'distance': 5.9,
      'rating': 4.3,
      'reviewCount': 167,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Jollof+Kitchen',
      'phone': '+44 20 8769 5432',
    },
    {
      'id': 'calabar-kitchen-clapham',
      'name': 'Calabar Kitchen - Clapham',
      'address': '45 Clapham High Street',
      'city': 'London',
      'postcode': 'SW4 7UR',
      'latitude': 51.4620,
      'longitude': -0.1380,
      'distance': 3.1,
      'rating': 4.6,
      'reviewCount': 223,
      'cuisineTypes': ['Nigerian', 'Contemporary'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Calabar+Kitchen',
      'phone': '+44 20 7622 6543',
    },

    // EAST LONDON (4 restaurants)
    {
      'id': 'enish-ilford',
      'name': 'Enish - Ilford',
      'address': '567 High Road',
      'city': 'London',
      'postcode': 'IG1 1UD',
      'latitude': 51.5590,
      'longitude': 0.0730,
      'distance': 9.2,
      'rating': 4.2,
      'reviewCount': 145,
      'cuisineTypes': ['Nigerian', 'West African'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Enish+Ilford',
      'phone': '+44 20 8478 4567',
    },
    {
      'id': 'african-pot-stratford',
      'name': 'African Pot - Stratford',
      'address': '123 The Broadway',
      'city': 'London',
      'postcode': 'E15 4BQ',
      'latitude': 51.5415,
      'longitude': -0.0030,
      'distance': 6.5,
      'rating': 4.3,
      'reviewCount': 178,
      'cuisineTypes': ['Nigerian', 'West African', 'Ghanaian'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=African+Pot',
      'phone': '+44 20 8534 3456',
    },
    {
      'id': 'naija-flavours-barking',
      'name': 'Naija Flavours - Barking',
      'address': '78 Ripple Road',
      'city': 'London',
      'postcode': 'IG11 7PG',
      'latitude': 51.5370,
      'longitude': 0.0810,
      'distance': 9.8,
      'rating': 4.1,
      'reviewCount': 134,
      'cuisineTypes': ['Nigerian', 'Traditional'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=Naija+Barking',
      'phone': '+44 20 8594 2345',
    },
    {
      'id': 'west-african-grill-newham',
      'name': 'West African Grill - Newham',
      'address': '234 Green Street',
      'city': 'London',
      'postcode': 'E13 9AP',
      'latitude': 51.5260,
      'longitude': 0.0270,
      'distance': 7.8,
      'rating': 4.4,
      'reviewCount': 189,
      'cuisineTypes': ['West African', 'Nigerian', 'Grill'],
      'hasDelivery': true,
      'hasTakeaway': true,
      'isOpenNow': true,
      'imageUrl': 'https://via.placeholder.com/300x200?text=West+African+Grill',
      'phone': '+44 20 8472 5678',
    },
  ];

  // Combine all restaurants
  final allRestaurants = [...hertfordshireRestaurants, ...londonRestaurants];

  debugPrint('📦 Importing ${allRestaurants.length} restaurants...');
  debugPrint('   - Hertfordshire: ${hertfordshireRestaurants.length}');
  debugPrint('   - London: ${londonRestaurants.length}');
  debugPrint('');

  int hertCount = 0;
  int londonCount = 0;

  // Import Hertfordshire restaurants
  debugPrint('🏘️  IMPORTING HERTFORDSHIRE RESTAURANTS...');
  for (var restaurant in hertfordshireRestaurants) {
    try {
      await firestore.collection('restaurants').doc(restaurant['id'] as String).set(restaurant);
      hertCount++;
      debugPrint('✅ [$hertCount/${hertfordshireRestaurants.length}] ${restaurant['name']}');
    } catch (e) {
      debugPrint('❌ Error: ${restaurant['name']} - $e');
    }
  }

  debugPrint('');
  debugPrint('🏙️  IMPORTING LONDON RESTAURANTS...');
  for (var restaurant in londonRestaurants) {
    try {
      await firestore.collection('restaurants').doc(restaurant['id'] as String).set(restaurant);
      londonCount++;
      debugPrint('✅ [$londonCount/${londonRestaurants.length}] ${restaurant['name']}');
    } catch (e) {
      debugPrint('❌ Error: ${restaurant['name']} - $e');
    }
  }

  debugPrint('');
  debugPrint('🎉 Import complete!');
  debugPrint('   - Hertfordshire: $hertCount restaurants');
  debugPrint('   - London: $londonCount restaurants');
  debugPrint('   - Total: ${hertCount + londonCount} restaurants');
}
