// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEHBu_RoEf3nZQX_peVgeVzd4UCrFIaM',
    appId: '1:620071589254:android:e672152b39d7c6704c8807',
    messagingSenderId: '620071589254',
    projectId: 'naija-food-finder-uk',
    storageBucket: 'naija-food-finder-uk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnD1T-G-kyU69AvFsF9fQZskukwDAfvk',
    appId: '1:620071589254:ios:169a819ca7e46e484c8807',
    messagingSenderId: '620071589254',
    projectId: 'naija-food-finder-uk',
    storageBucket: 'naija-food-finder-uk.firebasestorage.app',
    androidClientId: '620071589254-gfoe3r31j4p9v3rebavg97mp10du55tc.apps.googleusercontent.com',
    iosClientId: '620071589254-l528qj9oo3u0hoct5545i30idgg6rcer.apps.googleusercontent.com',
    iosBundleId: 'com.naijafoodfinder.naijaFoodFinderUk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEHBu_RoEf3nZQX_peVgeVzd4UCrFIaM',
    appId: '1:620071589254:web:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '620071589254',
    projectId: 'naija-food-finder-uk',
    storageBucket: 'naija-food-finder-uk.firebasestorage.app',
    authDomain: 'naija-food-finder-uk.firebaseapp.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnD1T-G-kyU69AvFsF9fQZskukwDAfvk',
    appId: '1:620071589254:ios:169a819ca7e46e484c8807',
    messagingSenderId: '620071589254',
    projectId: 'naija-food-finder-uk',
    storageBucket: 'naija-food-finder-uk.firebasestorage.app',
    androidClientId: '620071589254-gfoe3r31j4p9v3rebavg97mp10du55tc.apps.googleusercontent.com',
    iosClientId: '620071589254-l528qj9oo3u0hoct5545i30idgg6rcer.apps.googleusercontent.com',
    iosBundleId: 'com.naijafoodfinder.naijaFoodFinderUk',
  );

}